site_name: 2021.1 - SiGeD

repo_name: '2021.1 - SiGeD'
repo_url: 'https://github.com/FGA-GCES/2020-2-SiGeD'


extra_javascript:
  - assets/js/jquery.min.js
  - assets/js/jquery.zoom.min.js
  - assets/js/extra.js

extra_css:
  - assets/css/docs.css

nav:
  - Home: index.html
  - Documentação:
    - Home: home.md
    - Sprints:
      - Sprint 01: 'sprints/sprint1.md'
      - Sprint 02: 'sprints/sprint2.md'
      - Sprint 03: 'sprints/sprint3.md'
      - Sprint 04: 'sprints/sprint4.md'
      - Sprint 05: 'sprints/sprint5.md'
      - Sprint 06: 'sprints/sprint6.md'
      - Sprint 07: 'sprints/sprint7.md'
      - Apresentação Final: 'sprints/apresentacaoFinal'

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  
